
ARG NODE_VERSION=latest

FROM node:${NODE_VERSION}

WORKDIR /app

COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .env.docker* ./

RUN npm install --legacy-peer-deps

RUN npm i -g serve

COPY . .

RUN npm run build:docker

EXPOSE 3000

CMD [ "serve", "-s", "dist" ]